url: "https://youcancallmej.github.io/"
baseurl: 

# Site settings
title: Junseo Yang
email: jsy724724@gmail.com
description: "Developer. Full Stack. Always Student."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
  #  url: http://twitter.com/jekyllrb
  #- title: facebook
  #  url:
  - title: stack-overflow
    url: https://stackoverflow.com/users/11965087/user11965087
  - title: github
    url: https://github.com/YouCanCallMeJ
  - title: linkedin
    url: https://www.linkedin.com/in/junseo-yang-8878a6210/

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty