version: "3.3"

services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --force_polling --drafts --livereload --trace --disable-disk-cache
    ports:
      - "4000:4000"
    volumes:
      - ".:/srv/jekyll"